server:
  port: 8888

spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/exg?useUnicode=true&characterEncoding=utf-8
    username: exg
    password: guoguo311
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 1
    defaultAutoCommit: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

redis:
  single:
    host: localhost
    port: 6379
    timeout: 5000
    pool:
      minIdle: 10
      maxIdle: 10
      maxTotal: 100
      maxWaitMillis: 5000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
  cluster:
    nodes: 192.168.123.83:6381,192.168.123.83:6382,192.168.123.83:6383
    timeout: 5000
    expire: 120
    clusterPool:
      minIdle: 10
      maxIdle: 10
      maxTotal: 100
      maxWaitMillis: 5000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true

